"""Add Review Model

Revision ID: 774da8d6835d
Revises: 017b25ebacf0
Create Date: 2024-08-03 16:47:08.689677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774da8d6835d'
down_revision = '017b25ebacf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
